apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: chat
        tier: backend
        track: stable
    spec:
      containers:
        - name: chat
          image: 902415107800.dkr.ecr.us-east-1.amazonaws.com/llama:2.10
          ports:
            - name: app-port
              containerPort: 8000
          volumeMounts:
            - name: efs-volume-1
              mountPath: /efs_mounted
      imagePullSecrets:
        - name: ecr-secret
      volumes:
        - name: efs-volume-1
          persistentVolumeClaim:
            claimName: efs-claim100

---
apiVersion: v1
kind: Service
metadata:
  name: chat-backend-service
  labels:
    app.kubernetes.io/name: chat-backend-service
spec:
  type: ClusterIP
  selector:
    app: chat
    tier: backend
  ports:
    - name: svc-port
      port: 80
      targetPort: app-port
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
      tier: frontend
  template:
    metadata:
      labels:
        app: chat
        tier: frontend
    spec:
      containers:
      - name: react-frontend
        image: 902415107800.dkr.ecr.us-east-1.amazonaws.com/front_end:1.17
        ports:
            - name: app-port
              containerPort: 3000
      imagePullSecrets:
        - name: ecr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app.kubernetes.io/name: frontend-service
spec:
  type: ClusterIP
  selector:
    app: chat
    tier: frontend
  ports:
    - name: svc-port
      port: 80
      targetPort: app-port
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
      tier: chat-main
  template:
    metadata:
      labels:
        app: chat
        tier: chat-main
    spec:
      containers:
      - name: chat-main
        image: 902415107800.dkr.ecr.us-east-1.amazonaws.com/chat:3.9
        ports:
            - name: app-port
              containerPort: 5000
      imagePullSecrets:
        - name: ecr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: chat-main-service
  labels:
    app.kubernetes.io/name: chat-main-service
spec:
  type: ClusterIP
  selector:
    app: chat
    tier: chat-main
  ports:
    - name: svc-port
      port: 80
      targetPort: app-port
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatopenai-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
      tier: chatopenai-main
  template:
    metadata:
      labels:
        app: chat
        tier: chatopenai-main
    spec:
      containers:
      - name: chat-main
        image: 902415107800.dkr.ecr.us-east-1.amazonaws.com/chat-openai:1.5
        ports:
            - name: app-port
              containerPort: 4000
      imagePullSecrets:
        - name: ecr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: chatopenai-main-service
  labels:
    app.kubernetes.io/name: chatopenai-main-service
spec:
  type: ClusterIP
  selector:
    app: chat
    tier: chatopenai-main
  ports:
    - name: svc-port
      port: 80
      targetPort: app-port
      protocol: TCP