apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: chat
        tier: backend
        track: stable
    spec:
      containers:
        - name: chat
        # Add the address to your container repository
          image: 902415107800.dkr.ecr.us-east-1.amazonaws.com/chat:1.3
          ports:
            - name: http
              containerPort: 8000
      imagePullSecrets:
        - name: ecr-secret
        
---
apiVersion: v1
kind: Service
metadata:
  name: chat-backend-service
spec:
  selector:
    app: chat
    tier: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
      tier: frontend
  template:
    metadata:
      labels:
        app: chat
        tier: frontend
    spec:
      containers:
      - name: react-frontend
        image: 902415107800.dkr.ecr.us-east-1.amazonaws.com/front_end:1.12
        ports:
        - containerPort: 3000
      imagePullSecrets:
        - name: ecr-secret

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: chat
    tier: frontend
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000
