apiVersion: batch/v1
kind: Job
metadata:
  name: helm-upgrade
spec:
  template:
    spec:
      containers:
      - name: helm
        image: alpine/helm:latest
        command: ["helm", "upgrade", "--install", "ingress-nginx", "ingress-nginx", "--repo", "https://kubernetes.github.io/ingress-nginx", "--namespace", "ingress-nginx", "--create-namespace", "--set", "controller.hostPort.enabled=true"]
      restartPolicy: Never